baseURL = "https://www.yidajiabei.xyz"
title = "ä¸€å¤§åŠ è´"
theme = "hugo-coder"

languagecode = "zh"
defaultcontentlanguage = "zh"
hasCJKLanguage = true
enableRobotsTXT = false
enableEmoji = true
canonifyURLs = false

paginate = 300


pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pluralizelisttitles = false

FootnoteReturnLinkContents = "â†‘"

[markup.goldmark.renderer]
    unsafe= true

[outputs]
  page     = ["HTML", "AMP"]
  home     = ["HTML", "RSS"]
  section  = ["HTML"]
  taxonomyTerm = ["HTML"]
  taxonomy = ["HTML"]

[taxonomies]
  category = "categories"
  tech = "tech"
  life = "life"
  tag = "tags"

# URL ç»“æ„
# [permalinks]
#     categories = "/categories/:slug/"
#     tech = "/tech/:slug/"
#     life = "/life/:slug/"
#     tags = "/tags/:slug/"

[params]
    author = "ä¸€å¤§åŠ è´"
    info = "self ğŸ¶ dev"
    description = "Self-management + IT technology = build myself"
    keywords = "life,dev,developer,Self-management,IT technology"
    avatarurl = "images/me.png"
    logoImg = "images/me.png"
    header = "YIDAJIABEI.xyz"
    disable_comments = false
    twitter = "yidajiabei"
    github = "Gaotianhe"
    telegram = "yidajiabei"
    zhihu = "yidajiabei"

    favicon_32 = "images/f/favicon-32x32.png"
    favicon_16 = "images/f/favicon-16x16.png"
    
    
    ######################################
    # ä»…åœ¨ç”Ÿäº§ç¯å¢ƒä¸‹æ¸²æŸ“

    enableGoogleTagManagerWebPushr = true


    ######################################
    # æ–‡ç« åˆ†åŒºèŒƒå›´

    # è¯´æ˜ï¼šåˆ†åŒºçš„åå­—å³ç«™ç‚¹çš„ content ç›®å½•ä¸‹
    #      çš„æ–‡ä»¶å¤¹çš„åå­—ã€‚

    # mainSections = ["zh","en"]


    # footercontent = "self/dev/money"

    hidecredits = true
    hidecopyright = false

    siteLogo = "images/me.png"
    # series = true

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    # maxSeeAlsoItems = 100

    math = true
    custom_css = ["/css/main.css"]
    custom_js = ["/js/lazysizes.min.js"]

    dateFormat = "2006-01-02"

    # AMP
    amp = true
    ampElements = ["amp-ad","amp-analytics"]
    themeColor = "#000000"
    adsensePublisher = "ca-pub-8163003938382682"
    googleAnalytics = "UA-162698097-1"

# Comments on github issue
[params.utteranc]
    repo = "yidajiabei/www.yidajiabei.xyz"
    issue-term = "og:title"  #pathname
    theme = "github-light"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/Gaotianhe"
# [[params.social]]
#     name = "YouTube"
#     icon = "fab fa-youtube"
#     weight = 2
#     url = "https://www.youtube.com/channel/UCbg-Y24Z1H0nONW-bxgzv6w"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/yidajiabei"
[[params.social]]
    name = "Telegram"
    icon = "fab fa-telegram"
    weight = 4
    url = "https://t.me/s/yidajiabei"
[[params.social]]
    name = "WeChat"
    icon = "fab fa-weixin"
    weight = 5
    url = "/images/wechat.svg"
# [[params.social]]
#     name = "ZhiHu"
#     icon = "fab fa-zhihu"
#     weight = 6
#     url = "https://zhuanlan.zhihu.com/c_1262547332484161536"
[[params.social]]
    name = "Newsletter"
    icon = "fas fa-envelope"
    weight = 7
    url = "mailto:burgessnasa2019@gmail.com"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 8
    url = "index.xml"


[menu]
    ## èœå•æ 
    [[menu.main]]
        url = "/about/"
        name = "å…³äº"
        weight = 1
        pre = "internal"
    [[menu.main]]
        url = "/journal/"
        name = "æ—¥å¿—"
        weight = 2
        pre = "internal"
    [[menu.main]]
        url = "https://wiki.yidajiabei.xyz"
        name = "ç»´åŸº"
        weight = 3
        pre = "internal"
    [[menu.main]]
        url = "/bm/"
        name = "ä¹¦å½±"
        weight = 4
        pre = "internal"
    [[menu.main]]
        url = "/project/"
        name = "é¡¹ç›®"
        weight = 5
        pre = "internal"
    [[menu.main]]
        url = "/goal/"
        name = "ç›®æ ‡"
        weight = 6
        pre = "internal"
    [[menu.main]]
        url = "/posts/"
        name = "å½’æ¡£"
        weight = 7
        pre = "internal"
    [[menu.main]]
        url = "/feed/"
        name = "è®¢é˜…"
        weight = 8
        pre = "internal"
    [[menu.main]]
        weight = 9
        identifier = "lang-switcher"

##########################################
# è‡ªè¡Œæ·»åŠ çš„å¤šè¯­è¨€ç«™ç‚¹é…ç½®

# ä¸­æ–‡
[languages.zh]
    languageName = "Chinese"
    contentDir = "content/zh"
    weight = 1
    title = "ä¸€å¤§åŠ è´"

# è‹±æ–‡
[languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 2
    languageCode = "en-US"
    hasCJKLanguage = true
    title = "YIDAJIABEI"
[languages.en.taxonomies]
    category = "categories"
    tech = "tech"
    life = "life"

[languages.en.menu]
    [[languages.en.menu.main]]
        url = "/about/"
        name = "About"
        weight = 1
        pre = "internal"
    [[languages.en.menu.main]]
        url = "/journal/"
        name = "Journal"
        weight = 2
        pre = "internal"
    [[languages.en.menu.main]]
        url = "https://wiki.yidajiabei.xyz"
        name = "Wiki"
        weight = 3
        pre = "internal"
    [[languages.en.menu.main]]
        url = "/posts/"
        name = "Posts"
        weight = 4
        pre = "internal"
    [[languages.en.menu.main]]
        url = "/feed/"
        name = "Feed"
        weight = 5
        pre = "internal"
    [[languages.en.menu.main]]
        weight = 6
        identifier = "lang-switcher"

        
[languages.en.params]
    author = "YIDAJIABEI"
    info = "self ğŸ¶ dev"
    description = "Self-management + IT technology = build my passive income"
    keywords = "life,dev,developer,Self-management,IT technology"
    avatarurl = "images/me.png"
    logoImg = "images/me.png"
    header = "YIDAJIABEI.xyz"
