baseurl = "https://www.yidajiabei.xyz"
title = "ä¸€å¤§åŠ è´"
theme = ["hugo-notice","hugo-coder"]

languagecode = "zh-CN"
defaultcontentlanguage = "zh"
hasCJKLanguage = true
enableRobotsTXT = true
canonifyURLs = true

paginate = 300
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pluralizelisttitles = false

FootnoteReturnLinkContents = "â†‘"

[markup.goldmark.renderer]
    unsafe= true

[outputs]
  page     = ["HTML", "AMP"]
  home     = ["HTML", "RSS"]
  section  = ["HTML"]
  taxonomyTerm = ["HTML"]
  taxonomy = ["HTML"]

[taxonomies]
  category = "categories"
  tech = "tech"
  life = "life"

# URL ç»“æ„
# [permalinks]
#     categories = "/categories/:slug/"
#     tech = "/tech/:slug/"
#     life = "/life/:slug/"

[params]
    author = "ä¸€å¤§åŠ è´"
    info = "self ğŸ¶ dev"
    description = "Self-management + IT technology = build my passive income"
    keywords = "life,dev,developer,Self-management,IT technology"
    avatarurl = "images/me.png"
    logoImg = "images/me.png"
    header = "YIDAJIABEI.xyz"
    disable_comments = false
    twitter = "yidajiabei"
    github = "Gaotianhe"
    telegram = "yidajiabei"
    zhihu = "yidajiabei"

    favicon_32 = "images/f/favicon-32x32.png"
    favicon_16 = "images/f/favicon-16x16.png"

    # footercontent = "self/dev/money"

    hidecredits = true
    hidecopyright = false

    siteLogo = "images/me.png"
    # series = true

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    # maxSeeAlsoItems = 100

    math = true
    custom_css = ["/css/main.css"]
    custom_js = ["/js/lazysizes.min.js"]

    dateFormat = "2006-01-02"

    # AMP
    amp = false
    ampElements = ["amp-ad","amp-analytics"]
    themeColor = "#000000"
    adsensePublisher = "ca-pub-8163003938382682"
    googleAnalytics = "UA-162698097-1"

# Comments on github issue
[params.utteranc]
    repo = "yidajiabei/www.yidajiabei.xyz"
    issue-term = "og:title"  #pathname
    theme = "github-light"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/Gaotianhe"
# [[params.social]]
#     name = "YouTube"
#     icon = "fab fa-youtube"
#     weight = 2
#     url = "https://www.youtube.com/channel/UCbg-Y24Z1H0nONW-bxgzv6w"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/yidajiabei"
[[params.social]]
    name = "Telegram"
    icon = "fab fa-telegram"
    weight = 4
    url = "https://t.me/s/yidajiabei"
[[params.social]]
    name = "WeChat"
    icon = "fab fa-weixin"
    weight = 5
    url = "/images/wechat.svg"
[[params.social]]
    name = "ZhiHu"
    icon = "fab fa-zhihu"
    weight = 6
    url = "https://zhuanlan.zhihu.com/c_1262547332484161536"
[[params.social]]
    name = "Newsletter"
    icon = "fas fa-envelope"
    weight = 7
    url = "https://tinyletter.com/yidajiabei"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 8
    url = "index.xml"


[menu]
    ## èœå•æ 
    [[menu.main]]
        url = "/about/"
        name = "å…³äº"
        weight = 1
        pre = "internal"
    [[menu.main]]
        url = "https://www.yidajiabei.xyz/wiki/"
        name = "ç»´åŸº"
        weight = 2
        pre = "internal"
    [[menu.main]]
        url = "/bm/"
        name = "ä¹¦å½±"
        weight = 3
        pre = "internal"
    [[menu.main]]
        url = "/posts/"
        name = "å½’æ¡£"
        weight = 7
        pre = "internal"
    [[menu.main]]
        url = "/blogroll/"
        name = "å‹é“¾"
        weight = 8
        pre = "internal"
    [[menu.main]]
        weight = 11
        identifier = "lang-switcher"

##########################################
# è‡ªè¡Œæ·»åŠ çš„å¤šè¯­è¨€ç«™ç‚¹é…ç½®

# ä¸­æ–‡
[languages.zh]
    languageName = "Chinese"
    contentDir = "content/zh"
    weight = 1
    title = "ä¸€å¤§åŠ è´"

# è‹±æ–‡
[languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 2
    languageCode = "en-US"
    hasCJKLanguage = true
    title = "YIDAJIABEI"
[languages.en.taxonomies]
    category = "categories"
    tech = "tech"
    life = "life"

[languages.en.menu]
    [[languages.en.menu.main]]
        url = "/about/"
        name = "About"
        weight = 1
        pre = "internal"
    [[languages.en.menu.main]]
        url = "https://www.yidajiabei.xyz/wiki/#/"
        name = "Wiki"
        weight = 2
        pre = "internal"
    [[languages.en.menu.main]]
        url = "/posts/"
        name = "Posts"
        weight = 6
        pre = "internal"
    [[languages.en.menu.main]]
        weight = 8
        identifier = "lang-switcher"

        
[languages.en.params]
    author = "YIDAJIABEI"
    info = "self ğŸ¶ dev"
    description = "Self-management + IT technology = build my passive income"
    keywords = "life,dev,developer,Self-management,IT technology"
    avatarurl = "images/me.png"
    logoImg = "images/me.png"
    header = "YIDAJIABEI.xyz"



######################################
# åˆ†ç±»æ–¹å¼

categoryBy = "categories"
# [languages]
    
#         weight = 1
#         languagename = "Chinese"
#         

#         [languages.zh.params]
#             author = "é«˜å¤©è´º"
#             info = "self ğŸ¶ dev"
#             description = "ä¸€ä¸ªä¸ªäººåšå®¢"
#             keywords = "è‡ªæˆ‘ç®¡ç†ã€æ—¶é—´ç®¡ç†ã€GTDã€å†™ä½œã€ç¬”è®°ç®¡ç†ã€çŸ¥è¯†ç®¡ç†ã€è´¢åŠ¡ç®¡ç†ã€å…¨æ ˆå¼€å‘ã€SEO"
#             # footercontent = "self/dev/money"

#         [languages.zh.menu]

#             [[languages.zh.menu.main]]
#                 name = "å…³äº"
#                 weight = 1
#                 url = "zh/about/"
#             [[languages.zh.menu.main]]
#                 name = "æŠ€æœ¯"
#                 weight = 2
#                 url  = "zh/tech/"
#             [[languages.zh.menu.main]]
#                 name = "ç”Ÿæ´»"
#                 weight = 3
#                 url  = "zh/life/"
#             [[languages.zh.menu.main]]
#                 name = "å½’æ¡£"
#                 weight = 4
#                 url  = "zh/posts/"
#             [[languages.zh.menu.main]]
#                 name = "é¡¹ç›®"
#                 weight = 5
#                 url  = "/project/"
#             [[languages.zh.menu.main]]
#                 name = "ç›®æ ‡"
#                 weight = 6
#                 url  = "/goal/"
#             [[languages.zh.menu.main]]
#                 name = "åˆ†ç±»"
#                 weight = 7
#                 url  = "zh/categories/"
    
    
        # weight = 2
        # languagename = "English"
        # 

        # [languages.en.params]
        #     author = "Tianhe Gao"
        #     info = "self ğŸ¶ dev"
        #     description = "a personal blog"
        #     keywords = "self-managementã€time-managementã€GTDã€writingã€notesã€knowledgeã€full-stack"
        #     # footercontent = "self/dev/money"

        # [languages.en.menu]

        #     [[languages.en.menu.main]]
        #         name = "About"
        #         weight = 1
        #         url = "en/about/"
        #     [[languages.en.menu.main]]
        #         name = "Tech"
        #         weight = 2
        #         url  = "en/tech/"
        #     [[languages.en.menu.main]]
        #         name = "Life"
        #         weight = 3
        #         url  = "en/life/"
        #     [[languages.en.menu.main]]
        #         name = "Posts"
        #         weight = 4
        #         url  = "en/posts/"
        #     [[languages.en.menu.main]]
        #         name = "Project"
        #         weight = 5
        #         url  = "/project/"
        #     [[languages.en.menu.main]]
        #         name = "Goal"
        #         weight = 6
        #         url  = "/goal/"